linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: logur.dev/integration/zap

linters:
    enable-all: true
    disable:
        - funlen
        - gomnd
        - testpackage
